repos:
  -   repo: git://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
        - id: check-case-conflict
        - id: check-merge-conflict
        - id: check-symlinks
        - id: check-xml
        - id: check-yaml
        - id: detect-private-key
        - id: trailing-whitespace
        - id: debug-statements
        - id: end-of-file-fixer

  -   repo: https://github.com/ambv/black
      rev: 21.10b0
      hooks:
        - id: black
          language_version: python3.8
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ['--config=setup.cfg']
        additional_dependencies: [flake8-isort, flake8-bugbear]
        types: [python]
